FROM --platform=linux/amd64 node:18.16.1-alpine as builder

WORKDIR /home/node

COPY package*.json /home/node/

RUN npm install

COPY . /home/node/

RUN npm run build wolverine

FROM node:18.16.1-alpine as wolverine

WORKDIR /home/app

COPY --from=builder /home/node/dist/apps/wolverine/package*.json /home/app/

COPY --from=builder /home/node/dist/ /home/app/dist/

COPY --from=builder /home/node/test.js /home/app/

RUN npm ci --ignore-scripts

RUN apk --no-cache add curl

RUN npm install @nx/nx-linux-x64-gnu

CMD ["sh", "-c", "node dist/apps/wolverine/main.js"]
